language: python

sudo: false

install: 
    - pip install doc8
    - npm install -g write-good

script:
    - doc8 README.rst
    - doc8 SOURCES.rst
    - write-good README.rst --so --thereIs --cliches
    - write-good SOURCES.rst --so --thereIs --cliches
